language: cpp



os:
  - osx
  - linux



compiler:
  - gcc
  - clang



dist: trusty
osx_image: xcode9.1
sudo: required



addons:
    apt:
        packages:
          - cmake
          - curl
          - git
          - libx11-dev
          - libx11-xcb-dev
          - x11-utils



git:
    submodules: true



branches:
    only:
      - master



before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install freeimage assimp; fi
  - git checkout master
  - git submodule init
  - git submodule foreach git checkout master
  - mkdir build
  - cd build
  - cmake .. -G"Unix Makefiles"



script:
    make

