language: cpp



jobs:
  include:
    - os: linux
      dist: bionic
      arch: amd64
      compiler: gcc

    - os: linux
      dist: bionic
      arch: amd64
      compiler: clang

    - os: linux
      dist: bionic
      arch: arm64
      compiler: gcc

    - os: linux
      dist: bionic
      arch: arm64
      compiler: clang

    - os: linux
      dist: bionic
      arch: ppc64le
      compiler: gcc

    - os: linux
      dist: bionic
      arch: ppc64le
      compiler: clang

    - os: osx
      osx_image: xcode11.6
      arch: amd64
      compiler: clang

    - os: osx
      osx_image: xcode11.6
      arch: amd64
      compiler: gcc

    - os: windows
      compiler: gcc

    - os: windows
      compiler: clang



addons:
  apt:
    update: true
    packages:
      - cmake
      - curl
      - git
      - x11-utils
      - libx11-dev
      - libx11-xcb-dev
      - libxext-dev
      - libxcb1-dev
      - libxcb-image0-dev
      - libxcb-shm0-dev
      - subversion
      - libassimp-dev
      - libfreeimage-dev
  homebrew:
    update: true
    packages:
      - assimp
      - freeimage
      - libxkbcommon
  chocolatey:
    packages:
      - tortoisesvn


install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install tortoisesvn; fi


git:
  submodules: true


branches:
  only:
    - master


before_script:
  - git checkout master
  - git submodule init
  - git submodule foreach git checkout master
  - mkdir build
  - cd build
  - if [[ "$TRAVIS_OS_NAME" = "windows" ]] && [[ "$TRAVIS_COMPILER" != "gcc" ]]; then cmake ..; else cmake .. -G'Unix Makefiles'; fi


script:
  cmake --build . --config Release

