language: cpp



os:
  - osx
  - linux
  - windows



compiler:
  - gcc
  - clang



dist: xenial
osx_image: xcode10.1
sudo: required



addons:
    apt:
        update: true
        packages:
          - cmake
          - curl
          - git
          - libx11-dev
          - libx11-xcb-dev
          - x11-utils
          - libassimp-dev
          - libfreeimage-dev
    homebrew:
        update: true
        packages:
          - assimp
          - freeimage
    chocolatey:
        packages:
          - tortoisesvn



install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install tortoisesvn; fi



git:
    submodules: true



branches:
    only:
      - master



before_script:
  - git checkout master
  - git submodule init
  - git submodule foreach git checkout master
  - mkdir build
  - cd build
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then cmake .. -G'Unix Makefiles'; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" && "$CXX" == "g++" ]]; then cmake -G'Unix Makefiles' ..; else cmake ..; fi



script:
  cmake --build . --config Release --parallel

