language: cpp



jobs:
  include:
    - os: linux
      dist: bionic
      arch: amd64
      compiler: gcc

    - os: linux
      dist: bionic
      arch: amd64
      compiler: clang

    - os: linux
      dist: bionic
      arch: arm64
      compiler: gcc

    - os: linux
      dist: bionic
      arch: arm64
      compiler: clang

    - os: linux
      dist: bionic
      arch: ppc64le
      compiler: gcc

    - os: linux
      dist: bionic
      arch: ppc64le
      compiler: clang

    - os: osx
      osx_image: xcode11.6
      arch: amd64
      compiler: clang

    - os: osx
      osx_image: xcode11.6
      arch: amd64
      compiler: gcc

    - os: windows
      compiler: gcc

    - os: windows
      compiler: clang



addons:
  apt:
    update: true
    packages:
      - cmake
      - curl
      - git
      - x11-utils
      - libx11-dev
      - libx11-xcb-dev
      - libxext-dev
      - libxcb1-dev
      - libxcb-image0-dev
      - libxcb-shm0-dev
      - subversion
      - libassimp-dev
      - libfreeimage-dev
      - libfreetype6-dev
      - libglm-dev
      - libenet-dev
  homebrew:
    update: true
    packages:
      - assimp
      - freeimage
      - libxkbcommon
      - subversion
      - freetype
      - enet
      - glm
  chocolatey:
    packages:
      - tortoisesvn



before_install:
  - |-
    case $TRAVIS_OS_NAME in
      windows)
        [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
        choco uninstall -y mingw
        choco upgrade --no-progress -y msys2
        export msys2='cmd //C RefreshEnv.cmd '
        export msys2+='& set MSYS=winsymlinks:nativestrict '
        export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
        export mingw64="$msys2 -mingw64 -full-path -here -c "\"\$@"\" --"
        export msys2+=" -msys2 -c "\"\$@"\" --"
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-toolchain
        ## Install more MSYS2 packages from https://packages.msys2.org/base here
        taskkill //IM gpg-agent.exe //F  # https://travis-ci.community/t/4967
        $msys2 pacman -S --noconfirm --needed cmake mingw-w64-i686-assimp mingw-w64-x86_64-assimp mingw-w64-i686-freeimage mingw-w64-x86_64-freeimage
        export PATH=/C/tools/msys64/mingw64/bin:$PATH
        export MAKE=mingw32-make  # so that Autotools can find it
        ;;
    esac

install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install tortoisesvn; fi

before_cache:
  - |-
    case $TRAVIS_OS_NAME in
      windows)
        # https://unix.stackexchange.com/a/137322/107554
        $msys2 pacman --sync --clean --noconfirm
        ;;
    esac

cache:
  directories:
    - $HOME/AppData/Local/Temp/chocolatey
    - /C/tools/msys64



git:
  submodules: true

branches:
  only:
    - master



before_script:
  - git checkout master
  - git submodule init
  - git submodule foreach git checkout master
  - mkdir build
  - cd build
  - |-
    if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then
        cmake .. -G'Unix Makefiles'
    else
        if [[ "$TRAVIS_COMPILER" = "gcc" ]]; then
            cmake .. -G'Unix Makefiles' -D"CMAKE_MAKE_PROGRAM:PATH=/C/tools/msys64/mingw64/bin/mingw32-make"
        else
            cmake ..
        fi
    fi



script:
  cmake --build . --config Release

